version: '3.1'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    hostname: adminer.local
    ports:
      - "80:80"
    networks:
      - adminer_nw
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

    environment:
      - VIRTUAL_PROTO=fastcgi
      - DEFAULT_HOST=adminer.local

networks:
  adminer_nw:
    name: adminer_nw
    driver: bridge